### ISSUE TITLE
SwaggerResponseExample hiding null properties in Swagger UI

### ISSUE THREAD

**Issue by jlnpinheiro** [mattfrear/Swashbuckle.Examples#42] opened 2019-01-08 18:59 UTC
When my example type has a null property the Swagger UI ("Example value") is hiding this property. How can I show it?

**Comment by mattfrear** [comment] 2019-01-09 01:50
Hi, that is by design, as nulls aren't allowed in request examples according to the Swagger 2.0 spec. Is your null in a request example or a response example? Also, are you using the Swashbuckle.Examples NuGet package or the ASP.NET Core version?

**Comment by mattfrear** [comment] 2019-01-09 02:41
I have changed it so that nulls are now shown in response examples. Released in https://www.nuget.org/packages/Swashbuckle.Examples/3.11.0

**Closed as completed by mattfrear** 2019-01-09 02:41 UTC

**Comment by jlnpinheiro** [comment] 2019-01-09 02:49
Thanks for your help, my friend!
