### ISSUE TITLE
DescriptionOperationFilter does not work when UseFullTypeNameInSchemaIds is enabled in SwaggerConfig

### ISSUE THREAD

**Issue by guylevy** [mattfrear/Swashbuckle.Examples#36] opened 2018-07-05 21:10 UTC
Hi,

When the UseFullTypeNameInSchemaIds SwaggerConfig option is enabled, description of properties using the DescriptionOperationFilter  are not showing in swagger page. When disabling this option, descriptions are appearing again.
The option is enabled like this:
```
 GlobalConfiguration.Configuration
                               .EnableSwagger(c =>
                               {
c.UseFullTypeNameInSchemaIds();
}
```

Since we have multiple DTOs with the same name but under different namespaces so we have to enable the UseFullTypeNameInSchemaIds.

Cheers,
Guy

**Comment by mattfrear** [comment] 2018-07-06 08:07
Oh right, I didn’t know that option existed. I will look into this when I get a chance, which will be in about a week.

Matt

**Closed as completed** 2018-07-15 16:03 UTC

**Comment by mattfrear** [comment] 2018-07-15 16:10
Released in 3.9.2 https://www.nuget.org/packages/Swashbuckle.Examples/3.9.2

**Comment by mattfrear** [comment] 2018-07-15 18:55
I've ported this fix to Swashbuckle.AspNetCore.Filters too (v. 3.0.2)

**Comment by guylevy** [comment] 2018-07-19 12:44
Thanks for tackling it quickly!
Unfortunately, the change for this caused another issue that make the swagger docu generation throw an exception (see below). I also tried with 3.9.3 but I get the same error. The error occurs regardless of the UseFullTypeNameInSchemaIds flag.

Cheers,
Guy
```
500 : {
 "Message": "An error has occurred.",
 "ExceptionMessage": "Object reference not set to an instance of an object.",
 "ExceptionType": "System.NullReferenceException",
 "StackTrace": " at Swashbuckle.Examples.DescriptionOperationFilter.SetRequestModelDescriptions(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
 at Swashbuckle.Examples.DescriptionOperationFilter.Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
 at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDesc, SchemaRegistry schemaRegistry)
 at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)
 at Swashbuckle.Swagger.SwaggerGenerator.<>c__DisplayClass7.<GetSwagger>b__4(IGrouping`2 group)
 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
 at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)
 at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at additiv.Services.Host.Filters.AuthenticationHandler.<SendAsync>d__2.MoveNext() in C:\\GIT\\Skeleton-Wms\\ServiceLayer\\src\\additiv.Services.Host\\Filters\\AuthenticationHandler.cs:line 35
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at additiv.Services.Host.Swagger.SwaggerAuthenticationHandler.<SendAsync>d__0.MoveNext() in C:\\GIT\\Skeleton-Wms\\ServiceLayer\\src\\additiv.Services.Host\\Swagger\\SwaggerAuthenticationHandler.cs:line 21
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.HttpServer.<SendAsync>d__24.MoveNext()"
 } http://localhost:52648/swagger/docs/v1 
```

**Comment by mattfrear** [comment] 2018-07-19 13:32
Hmm, I'm not seeing that locally. So 3.9.1 doesn't throw an exception?

I might need your help to repro it locally - can you post what your controller looks like, and the relevant request and response models?

**Comment by mattfrear** [comment] 2018-07-19 20:48
I wasn't able to reproduce this locally, but I've added a null check based on your stack trace above, so maybe that fixed it for you?

Please try https://www.nuget.org/packages/Swashbuckle.Examples/3.9.4

**Comment by guylevy** [comment] 2018-07-23 14:40
Sorry for late reply. I can confirm that with 3.9.4 it works correctly with and without UseFullTypeNameInSchemaIds.

Any idea what could be the trigger for this on our controllers or respond / request classes?

**Comment by mattfrear** [comment] 2018-07-24 07:40
> Any idea what could be the trigger for this on our controllers or respond / request classes?

Sorry, I don't understand this question.

PS. maybe you need to click the Notifications button on the GitHub page on the right?
