### ISSUE TITLE
One request type in two actions

### ISSUE THREAD

**Issue by askrinnik** [mattfrear/Swashbuckle.Examples#64] opened 2022-10-13 18:03 UTC
Hi.
I have a REST API application on .NET Framework 4.8
Swashbuckle.Examples 4.1.0 is installed
My controller has POST and PUT actions, which accept **the same** request type.
I wanted to implement two different examples for the actions. I put [SwaggerRequestExample] attribute to the POST and PUT methods. But they use different IExamplesProvider implementations:
```
    [HttpPost]
    [ActionName("CreateAccount")]
    [SwaggerRequestExample(typeof(Account), typeof(CreateAccountExample)]
    public HttpResponseMessage Post([FromBody] Account value)
    {
     ...
    }

    [HttpPut]
    [ActionName("EditAccount_ID")]
    [SwaggerRequestExample(typeof(Account), typeof(EditAccountExample),)]
    public HttpResponseMessage Put(int id, [FromBody] Account value)
    {
       ...
    }
```
But in fact, I see **the CreateAccountExample ** in both actions.
If I remove the SwaggerRequestExample attribute from the PUT action, I still see **the CreateAccountExample** in the PUT action. 
It looks like the attribute using in one action overwrites examples in all actions with the same request type.
Is it correct behavior?

**Comment by mattfrear** [comment] 2022-10-13 19:45
Hello

This is a [known issue](https://github.com/mattfrear/Swashbuckle.Examples#known-issues) due to a limitation of Swagger 2.0.

>    For requests, in the Swagger 2.0 spec there is only one schema for each request object defined across all the API endpoints.

Duplicate of #63.

**Closed as not planned by mattfrear** 2022-10-13 19:45 UTC

**Comment by askrinnik** [comment] 2022-10-14 10:20
Thank you for the explanation.
Just to clarify, does it work in Swashbuckle.AspNetCore? It also works with Swagger 2.0 spec

**Comment by mattfrear** [comment] 2022-10-17 00:23
I'm pretty sure it works in Swashbuckle.AspNetCore and using my Swashbuckle.AspNetCore.Filters package, but only if you're using OpenApi 3.0 (which is the default). 

If you're telling Swashbuckle.AspNetCore to use Swagger 2.0 (via `c.SerializeAsV2 = true;`) then it doesn't work.
