### ISSUE TITLE
Example response injects "application/json" property 

### ISSUE THREAD

**Issue by jerchap** [mattfrear/Swashbuckle.Examples#47] opened 2019-09-27 23:27 UTC
I've set up my Swagger examples:
`[SwaggerResponseExample(HttpStatusCode.OK,typeof(WebAPI.Examples.APIResponseExample))]`

Now the SwaggerUI injects "application/json" as the property of a wrapper object:

```
 Response Class (Status 200)
 Successful operation.
 
 ModelExample Value
 {
   "application/json": {
     "Url": "http://mysite",
     "XmlContent": "<ClinicalDocument xmlns=\"urn:hl7 - org:v3\" moodCode=\"EVN\" classCode=\"DOCCLIN\">...</ClinicalDocument>"
   }
 }
```

I would have expected it to render as:

```
 Response Class (Status 200)
 Successful operation.
 
 ModelExample Value
 {
     "Url": "http://mysite",
     "XmlContent": "<ClinicalDocument xmlns=\"urn:hl7 - org:v3\" moodCode=\"EVN\" classCode=\"DOCCLIN\">...</ClinicalDocument>"
 }
```

My example class looks like this:
```
public class APIResponseExample : Swashbuckle.Examples.IExamplesProvider
{
    public object GetExamples()
    {
        return new Models.APIResponse()
        {
            XmlContent= "<ClinicalDocument xmlns=\"urn:hl7 - org:v3\" moodCode=\"EVN\" classCode=\"DOCCLIN\">...</ClinicalDocument>",
            Url = "http://mysite"
        };
    }
}
```

**Comment by mattfrear** [comment] 2019-09-29 09:03
That is by design, and is a Known Issue https://github.com/mattfrear/Swashbuckle.Examples#known-issues

FYI the display issue was fixed in the ASP.NET Core version (Swashbuckle.AspNetCore.Filters)

**Closed as completed by mattfrear** 2019-09-29 09:03 UTC

**Comment by jerchap** [comment] 2019-09-30 16:16
hmm.  that kind of renders the example a bit useless.  You say it was fixed in Core but can't be fixed in the framework version.  argggg :)

**Comment by mattfrear** [comment] 2019-09-30 22:37
Yeah, because the bug is in swagger-ui which is a dependency of the Swashbuckle package. So you would need to update the version of swagger-ui which Swashbuckle uses to fix the bug. Good luck with that.
