### ISSUE TITLE
Not able to create a request example for string[] or List<string> 

### ISSUE THREAD

**Issue by sturlath** [mattfrear/Swashbuckle.Examples#53] opened 2020-05-20 10:42 UTC
I have an API looking like this

` 
     public async Task<IActionResult> Batch([FromQuery] string[] entries)
`  

where I am trying to add SwaggerRequestExample attribute like this

`  
   [SwaggerRequestExample(typeof(string[]),typeof(BatchRequestArrayExample))]
` 

with 

` 
    public class BatchRequestArrayExample : IExamplesProvider<string[]>
    {
        public string[] GetExamples()
        {
            return new string[] { "ent1", "ent2", "ent3" };
        }
    }
` 

But swagger doesn't show me these examples. What am I doing wrong? I have also tried it with List<string>.

 Note I have a working SwaggerResponseExample so my general setup seems to be good.

**Comment by mattfrear** [comment] 2020-05-20 19:52
Lists are a bit tricky. See the Readme. I’m not sure if List<string> will work.

https://github.com/mattfrear/Swashbuckle.Examples#list-request-examples

PS. this package is old, if you're using .NET Core you'll want to use Swashbuckle.AspNetCore.Filters instead.

**Comment by sturlath** [comment] 2020-05-21 14:39
Thank for your answer. And yes in the meantime I found the Filters one but have been unable to make that work. 

Am I doing this wrong? Btw I like this syntax much better!

```csharp
/// <summary>
/// Retrieves a specific product by unique id
/// </summary>
/// <remarks>Awesomeness!</remarks>
/// <param name="ids" example="some ids"></param>
/// <response code="200">Product created</response>
[HttpGet]
[ProducesResponseType(typeof(BatchResponseDTO), 200)]
public BatchResponseDTO GetById([FromQuery] List<string> ids)
{
    return new BatchResponseDTO() { };
}
```
I only get this here.. it works fine if I just have a string and not list/array

![image](https://user-images.githubusercontent.com/2386572/82569858-53a22880-9b70-11ea-8201-e16dad1d0fc0.png)

**Comment by sturlath** [comment] 2020-05-21 14:43
Ok found https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#list-request-examples going to try that out now

**Comment by sturlath** [comment] 2020-05-21 14:57
Nobs... not getting it to work. What am I doing wrong?
I found an example of this here (although that seems to be an enum dropdown..) http://petstore.swagger.io/#/pet/findPetsByStatus but am at this moment unable to find any code that could help me.

```csharp
/// <summary>
/// GetById
/// </summary>
[HttpGet]
[SwaggerRequestExample(typeof(string), typeof(RequestListExample), jsonConverter: typeof(StringEnumConverter))]
[ProducesResponseType(typeof(ResponseDTO), 200)]
public ResponseDTO GetById([FromQuery] List<string> ids)
{
    return new ResponseDTO() { };
}

// where this is the example 

public class RequestListExample: IExamplesProvider<string>
{
    public string GetExamples()
    {
        return "some id's"; 
    }
}
```

**Comment by mattfrear** [comment] 2020-05-22 09:07
Closing here since the issue is opened in Swashbuckle.AspNetCore.

**Closed as completed by mattfrear** 2020-05-22 09:07 UTC
