### ISSUE TITLE
SwaggerRequestExample  How to use??

### ISSUE THREAD

**Issue by seongguk92** [mattfrear/Swashbuckle.Examples#58] opened 2021-09-17 07:37 UTC
I'm now SwaggerRequestExample
Is using
There is no display in example Help.

~~~cs
    public class DictionaryContainer
    {
        public Dictionary<string, object> Dict;
    }
~~~

~~~cs
    public class TestExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var dict = new Dictionary<string, object>
            {
                {"IntVal", 13},
                {"BoolVal", true},
                {"GuidVal", Guid.Parse("1a0bdb34-a56a-439b-a8e6-6abd684dc817")}
            };

            return new DictionaryContainer { Dict = dict };
        }
    }
~~~

~~~cs
        [SwaggerRequestExample(typeof(DictionaryContainer), typeof(TestExample))]
        public IActionResult UpdateMembers([FromBody]DictionaryContainer dictContainer)
~~~

![image](https://user-images.githubusercontent.com/18062612/133744092-65b35bde-5c4d-4b56-8ca6-eddfa1073216.png)

**Comment by seongguk92** [comment] 2021-09-17 07:48
![image](https://user-images.githubusercontent.com/18062612/133745254-99162401-792f-4748-9e26-c453d8b0a8be.png)

![image](https://user-images.githubusercontent.com/18062612/133745614-1853a48c-42d5-4c8b-88f7-8802ef831639.png)

![image](https://user-images.githubusercontent.com/18062612/133745329-bbbd42f0-e2c5-4708-8872-9e49da04565a.png)


![image](https://user-images.githubusercontent.com/18062612/133745961-b6f30261-4625-4928-a423-643fbacc826f.png)

ㅠ_ㅠ

**Comment by mattfrear** [comment] 2021-09-20 04:05
Hello

Are you using ASP.NET or ASP.NET Core? If you are using .NET Core then you will probably want to use https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters instead of this project.

If you're using .NET Framework then this is the correct project. It sounds like the issue you have raised is a duplicate of https://github.com/mattfrear/Swashbuckle.Examples/issues/45 

Matt

**Comment by seongguk92** [comment] 2021-09-21 06:36
thank you. @mattfrear 
The .net core version is correct.
I will ask you a question on that project.

**Closed as completed** 2021-09-21 06:38 UTC
